#!/usr/bin/env bash
# Installs nginx and serves a Hello World! page on port 80

# Install nginx
apt-get update -y
apt-get install -y nginx

# Set up Hello World! in the default nginx index
echo "Hello World!" > /var/www/html/index.html

# Restart nginx without systemctl
service nginx restart
