#!/usr/bin/env bash
# Configures a new Ubuntu server with Nginx and adds a custom HTTP header with hostname

# Ignore shellcheck warning for SC2154 (hostname vars)
# shellcheck disable=SC2154

# Update and install nginx
apt-get update -y
apt-get install nginx -y

# Set a custom HTTP header with the server's hostname
echo "add_header X-Served-By \$hostname;" | tee /etc/nginx/conf.d/custom-header.conf

# Restart nginx to apply changes
service nginx restart
